server:
  port: 8080
  context-path: /demo
  tomcat:
    uri-encoding: UTF-8
spring:
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
RSA:
  private_key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIulr4TrtnEzySV5N6fn6FSVbTDGvCouwyfMuS4srXiMFQgRV8ETlcQu1o5ILSOkvww8Vc0n9IRABVe4k/aVRHbKOZMq6TNZKPak7RAyp5AzLImD0hzEXq0CsSTNH9U47qki7T0LhsQuku8AouGmP4USMEkpoHnAsZpZpNi71cBDAgMBAAECgYAeG8D2FaQmUBYEQFhhmTycUANUyuRy69Yj1J3weK2GGh3GuYaEGGbn/3k/AAzLbI/MYY3WR9EOWodMXH16YsB50kdiv44YrUOjvYxXNcLoAzTxNdZ4A+dxEnITFtWs3uUfWP9y71hFQUNPLgWxVAOVhmH3CEVIh2ry2LTYr8qnkQJBAM+6xXc2B4Hm/ako+fb1KMhrGVGwXqs9f5qBh5wzXnQhZV+Kh8DeydLNP5fJP+8XZEG5ivw8iRrTLQmSBxuGBz8CQQCsGORne4KZU5CIZHL05ERyvwoJDBOkY/DS/GLfYZSm+wZqTjyUHmtPshw8OqT7XuM3KbfLsfnENPzPOkDkaKn9AkBW6XIM+pIRi6+9wuMyrEgv8n9Zak1xn/1vi5pNhECUnhRn8PHzhEM066Mbwpv5UPQle5fnCPzkOE6znmFS5rTJAkEAjKbDdXfSIvHS/EXsVg2Bi65qyz4dh4tOtYEkZaDg1x/t/E/43q2F0tqkjOz5DaBdXyYvWsEYeq07uTnI82Q/GQJAOWKXAWGHutoEziR0QJ7bE2FXYq6JWMZ+KbcEWbuvJYXi2j6k9CVNFPnEMLtzKLFTEu5qtz6ru0kS7ZCxNo2PBw==
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLpa+E67ZxM8kleTen5+hUlW0wxrwqLsMnzLkuLK14jBUIEVfBE5XELtaOSC0jpL8MPFXNJ/SEQAVXuJP2lUR2yjmTKukzWSj2pO0QMqeQMyyJg9IcxF6tArEkzR/VOO6pIu09C4bELpLvAKLhpj+FEjBJKaB5wLGaWaTYu9XAQwIDAQAB