// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.login.req;

import com.config.decodeAni.DecodeParamType;
import com.config.decodeAni.DecodeParam;

public class UserReq {
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @DecodeParam(type = DecodeParamType.BANK_CARD)
    private String name;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    private String firstName;
    @Override
    public String toString() {
        return this.name+":"+this.firstName;
    }

}
